{{- if .Values.mediaServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cleo.fullname" . }}-media-server
  labels:
    {{- include "cleo.labels" . | nindent 4 }}
    app.kubernetes.io/component: media-server
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cleo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: media-server
{{- end }}
